fixing stickers delete function
Dmeiry/skitick-backend pull request #5
Opened 2024-08-26 12:00 UTC by Dmeiry

2024-08-26 12:13 UTC, Hussain-AboAlamal commented on controllers/stickersController.js
> +             const setstatus = { status: "2" };
create Enum for statuses code instead writing the values everywhere

2024-09-09 07:49 UTC, MahmoudDawoodSWE requested changes

2024-09-09 07:49 UTC, MahmoudDawoodSWE commented on constants/statusCodes.js
move this into new file

2024-09-09 08:09 UTC, MahmoudDawoodSWE approved these changes

2024-09-09 08:09 UTC, merged